version: '3.8'
services:
  pg:
    image: postgres:12.5
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${EXTERNAL_DB_PORT}:5432
    volumes:
      - pg_volume:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    ports:
      - ${REST_PORT}:${REST_PORT}
    env_file:
      - .env
    depends_on:
      - pg
    environment: # link to PG container
      - DB_HOST=pg
      - DB_PORT=5432
    stop_grace_period: 1m
    healthcheck:
      test: 'curl localhost:${REST_PORT}'
      start_period: 20s
      interval: 10s
      retries: 4
#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - ${FE_PORT}:${FE_PORT}
  nginx:
    container_name: loadbalancer-nginx
    image: falkot26/takeuseat:nginx
    build:
      context: ./nginx
    restart: always
    network_mode: host
    volumes:
      # Webpages static sources
      - /var/www:/var/www
volumes:
  pg_volume:
  redis-data:
